### ISSUE TITLE
Parser fails on multidimensional arrays

### ISSUE THREAD

**Issue by henkelma** [christoph2/pyA2L#21]
```python
DATA='''/begin CHARACTERISTIC TEST[0][0].TEST
         "TEST[FL,0].TEST"
         VALUE
         0x0003237C
         _HELLO
         30
         _TEST
         -18
         12
         DISPLAY_IDENTIFIER TEST[FL_0].TEST
         FORMAT "%3.1"
      /end CHARACTERISTIC'''

parser = ParserWrapper('a2l', 'characteristic', A2LListener, debug = False)
session = parser.parseFromString(DATA)
```
Fails with:
line 1:29 mismatched input '[' expecting STRING

Probably caused by:
```
partialIdentifier:
    i = IDENT (a = arraySpecifier)?
    ;
```
in a2l.g4

**Comment by henkelma** [comment]
Man, you are really fast. Thanks a lot for caring.

In the meantime I started working on a patch. Your change only fixes it partly, because the additional array dimensions get lost in the identifier. As far as I can tell it additionally needs to record the array identifiers with something like (a += arraySpecifier)* and also 

```
   def exitArraySpecifier(self, ctx):
        if ctx.i is not None:
            value = ctx.i.text
        elif ctx.n is not None:
            value = ctx.n.text
        else:
            value = None
        ctx.value = value
```

in a2l_listener.py needs to be updated accordingly.

Do you think my assumptions are correct, would you like to fix it?

**Comment by henkelma** [comment]
OK, here are my suggested changes:

a2l.g4:

` (a += arraySpecifier)*`

a2l_listener.py:

```python
    def exitPartialIdentifier(self, ctx):
        text = ctx.i.text if ctx.i else None

        result = ""
        for element in ctx.a:
            result += "[{}]".format(element.value)

        ctx.value = text + result

```

I'm just unsure about the corner case with empty text. Maybe it is better to assign "" (an empty string) instead of None to text.

**Comment by christoph2** [comment]
Great!
I've just added your changes.
